### ISSUE TITLE
Reset button for statistics

### ISSUE THREAD

**Issue by vartanbeno** [OlivierTD/team-rocket#150]
As a user, I would like to have a reset button that would reset the statistics accumulated on all podcasts
[SP: 3] 
[Value: high]
[Risk: low]

**Tasks breakdown:**
- Create "Reset" button.
- Code in its functionality.

**Testing:**

todo

**Demonstration Steps:**
1 - Navigate to the Statistics page from the Nav drawer.
2a - Assuming the user is already subscribed to at least one podcast, there should be a button that appears on the page with the text "Reset All Stats" which the user could press on if they like.
2b - If the user isn't subscribed to any podcasts, there will be a message encouraging the user to subscribe to one or more to start accumulating statistics.

**Comment by guipadua** [comment]
Not demoed, issues with DB. Maybe will make it to release meeting.

**Comment by vartanbeno** [comment]
Updated the StatisticsFragment to include new methods.
![screen shot 2018-04-18 at 4 15 17 pm](https://user-images.githubusercontent.com/23425661/38955891-eabfb9f0-4323-11e8-86e1-17ff9d63e896.png)
